export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const UPDATE_ITEM_QTY = 'UPDATE_ITEM_QTY';
export const FILTER_BY_SEARCH = 'FILTER_BY_SEARCH';
export const POPULATE_PRODUCTS = 'POPULATE_PRODUCTS';
export const POPULATE_FILTER_PARAMS = 'POPULATE_FILTER_PARAMS';
